//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Localization.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainingTracker.Localization.Resources.Shared.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked. Try again after {0}..
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the exercise..
        /// </summary>
        public static string AddExerciseError {
            get {
                return ResourceManager.GetString("AddExerciseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise added successfully..
        /// </summary>
        public static string AddExerciseSuccess {
            get {
                return ResourceManager.GetString("AddExerciseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the goal..
        /// </summary>
        public static string AddUserGoalError {
            get {
                return ResourceManager.GetString("AddUserGoalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal added successfully..
        /// </summary>
        public static string AddUserGoalSuccess {
            get {
                return ResourceManager.GetString("AddUserGoalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the progress..
        /// </summary>
        public static string AddUserProgressError {
            get {
                return ResourceManager.GetString("AddUserProgressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress added successfully..
        /// </summary>
        public static string AddUserProgressSuccess {
            get {
                return ResourceManager.GetString("AddUserProgressSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the workout..
        /// </summary>
        public static string AddWorkoutError {
            get {
                return ResourceManager.GetString("AddWorkoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout added successfully..
        /// </summary>
        public static string AddWorkoutSuccess {
            get {
                return ResourceManager.GetString("AddWorkoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the account..
        /// </summary>
        public static string DeleteAccountError {
            get {
                return ResourceManager.GetString("DeleteAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted successfully..
        /// </summary>
        public static string DeleteAccountSuccess {
            get {
                return ResourceManager.GetString("DeleteAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the goal..
        /// </summary>
        public static string DeleteUserGoalError {
            get {
                return ResourceManager.GetString("DeleteUserGoalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal deleted successfully..
        /// </summary>
        public static string DeleteUserGoalSuccess {
            get {
                return ResourceManager.GetString("DeleteUserGoalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the workout..
        /// </summary>
        public static string DeleteWorkoutError {
            get {
                return ResourceManager.GetString("DeleteWorkoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout deleted successfully..
        /// </summary>
        public static string DeleteWorkoutSuccess {
            get {
                return ResourceManager.GetString("DeleteWorkoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be longer then 500 characters..
        /// </summary>
        public static string Description500MaxLength {
            get {
                return ResourceManager.GetString("Description500MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while editing the goal..
        /// </summary>
        public static string EditUserGoalError {
            get {
                return ResourceManager.GetString("EditUserGoalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal edited successfully..
        /// </summary>
        public static string EditUserGoalSuccess {
            get {
                return ResourceManager.GetString("EditUserGoalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while editing the workout..
        /// </summary>
        public static string EditWorkoutError {
            get {
                return ResourceManager.GetString("EditWorkoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout updated successfully..
        /// </summary>
        public static string EditWorkoutSuccess {
            get {
                return ResourceManager.GetString("EditWorkoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorWhileProcessing {
            get {
                return ResourceManager.GetString("ErrorWhileProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender must be Male of Female..
        /// </summary>
        public static string GenderValidation {
            get {
                return ResourceManager.GetString("GenderValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal date must be in the future..
        /// </summary>
        public static string GoalDateValidation {
            get {
                return ResourceManager.GetString("GoalDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height must be between 50 cm and 300 cm..
        /// </summary>
        public static string HeightValidation {
            get {
                return ResourceManager.GetString("HeightValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired refresh token..
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid goal ID..
        /// </summary>
        public static string InvalidUserGoalID {
            get {
                return ResourceManager.GetString("InvalidUserGoalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid workout ID..
        /// </summary>
        public static string InvalidWorkoutID {
            get {
                return ResourceManager.GetString("InvalidWorkoutID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out successfully..
        /// </summary>
        public static string LoggedOutSuccess {
            get {
                return ResourceManager.GetString("LoggedOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while logging in..
        /// </summary>
        public static string LoggingError {
            get {
                return ResourceManager.GetString("LoggingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one exercise must be included..
        /// </summary>
        public static string MinExercisesValidation {
            get {
                return ResourceManager.GetString("MinExercisesValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions must be at least 1..
        /// </summary>
        public static string MinRepetitionsValidation {
            get {
                return ResourceManager.GetString("MinRepetitionsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets must be at least 1..
        /// </summary>
        public static string MinSetsValidation {
            get {
                return ResourceManager.GetString("MinSetsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be longer than 50 characters..
        /// </summary>
        public static string Name50MaxLength {
            get {
                return ResourceManager.GetString("Name50MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the password..
        /// </summary>
        public static string PasswordChangeError {
            get {
                return ResourceManager.GetString("PasswordChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while recovering the password..
        /// </summary>
        public static string PasswordRecoveryEmailError {
            get {
                return ResourceManager.GetString("PasswordRecoveryEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery email sent successfully..
        /// </summary>
        public static string PasswordRecoveryEmailSuccess {
            get {
                return ResourceManager.GetString("PasswordRecoveryEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest time must be between 0 and 60 minutes..
        /// </summary>
        public static string RestTimeValidation {
            get {
                return ResourceManager.GetString("RestTimeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always looking out for your physical and mental well-being.
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        public static string SuccessOperation {
            get {
                return ResourceManager.GetString("SuccessOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target value must be greater than zero..
        /// </summary>
        public static string TargetValuePositiveValidation {
            get {
                return ResourceManager.GetString("TargetValuePositiveValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access..
        /// </summary>
        public static string UnauthAccess {
            get {
                return ResourceManager.GetString("UnauthAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises in a workout must be unique (no repetitions)..
        /// </summary>
        public static string UniqueExercisesValidation {
            get {
                return ResourceManager.GetString("UniqueExercisesValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal not found..
        /// </summary>
        public static string UserGoalNotFound {
            get {
                return ResourceManager.GetString("UserGoalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while registering the user..
        /// </summary>
        public static string UserRegisterError {
            get {
                return ResourceManager.GetString("UserRegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully..
        /// </summary>
        public static string UserRegisterSuccess {
            get {
                return ResourceManager.GetString("UserRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed..
        /// </summary>
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be a positive number..
        /// </summary>
        public static string WeightValidation {
            get {
                return ResourceManager.GetString("WeightValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout not found..
        /// </summary>
        public static string WorkoutNotFound {
            get {
                return ResourceManager.GetString("WorkoutNotFound", resourceCulture);
            }
        }
    }
}
